version: "3"

services:
  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes: 
      - .:/app
    ports: 
      - 8000:8000
    depends_on: 
      pgdb:
        condition: service_healthy
    links:
      - pgdb

  pgdb:
      image: postgres
      container_name: pgdb
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      ports:
        - "5432:5432"
      volumes: 
        - .dbdata:/var/lib/postgresql/data
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 5s
        timeout: 5s
        retries: 5
