version: "3"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes: 
      - .:/app
    ports: 
      - 8000:8000
    depends_on: 
      - db

  db:
    image: mysql
    restart: always
    ports:
      - 33066:3306
    environment:
      MYSQL_DATABASE: admin
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
