# Generated by Django 3.2.8 on 2021-10-16 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('date', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=5)),
                ('duration', models.CharField(max_length=5)),
                ('location', models.CharField(max_length=100)),
                ('sportType', models.CharField(choices=[('soccer', 'Soccer'), ('basketball', 'Basketball')], max_length=50)),
                ('numOfPlayers', models.IntegerField()),
                ('status', models.CharField(default='UPCOMING', max_length=10)),
                ('applicants', models.ManyToManyField(related_name='appliedTo', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
                ('followers', models.ManyToManyField(related_name='followedEvents', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='participatingIn', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date', '-time'),
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
