version: "3.8"

services: 
    app:
        build: 
            context: .
            dockerfile: Dockerfile
        volumes: 
            - .:/app
        ports:
            - 3000:3000
        image: app:app-dev
        container_name: app-dev
        command: npm start