# Generated by Django 3.2.8 on 2022-01-02 17:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentpost',
            name='creationDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
