# Generated by Django 3.2.8 on 2021-12-31 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentpost',
            name='contact',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='equipmentpost',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='equipmentpost',
            name='sportType',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentpost',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentpost',
            name='location',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='equipmentpost',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
