# Generated by Django 3.2.8 on 2021-11-30 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_auto_20211127_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('1', 'Create'), ('4', 'Delete'), ('5', 'Follow'), ('6', 'Join'), ('7', 'Update')], max_length=10)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='activities', to='events.event')),
            ],
            options={
                'ordering': ['performed_at'],
            },
        ),
    ]
