# Generated by Django 3.2.8 on 2021-11-30 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_auto_20211127_1539'),
        ('activity_handler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventactivity',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventactivity',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='events.event'),
        ),
        migrations.AlterField(
            model_name='eventactivity',
            name='type',
            field=models.CharField(choices=[('1', 'Create'), ('2', 'Delete'), ('3', 'Follow'), ('4', 'Apply'), ('5', 'Update')], max_length=10),
        ),
    ]
