# Generated by Django 3.2.8 on 2021-11-02 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('date', models.CharField(max_length=12)),
                ('time', models.CharField(max_length=5)),
                ('duration', models.CharField(max_length=5)),
                ('location', models.CharField(max_length=50)),
                ('sportType', models.CharField(max_length=30)),
                ('maxPlayers', models.IntegerField()),
                ('applicants', models.ManyToManyField(related_name='applied', to=settings.AUTH_USER_MODEL)),
                ('followers', models.ManyToManyField(related_name='following', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(related_name='going', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('body', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.eventbody')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
