# Generated by Django 3.2.8 on 2021-11-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventbody',
            name='followers',
        ),
        migrations.AddField(
            model_name='eventbody',
            name='skill_level',
            field=models.CharField(choices=[('1', 'Beginner'), ('2', 'Intermediate'), ('3', 'Advanced')], default='Beginner', max_length=10),
        ),
    ]
