# Generated by Django 3.2.8 on 2021-11-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbody',
            name='date',
            field=models.DateField(),
        ),
    ]
