# Generated by Django 3.2.8 on 2021-10-21 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.CharField(max_length=5),
        ),
    ]
