# Generated by Django 3.2.8 on 2021-11-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_eventbody_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbody',
            name='duration',
            field=models.TimeField(),
        ),
    ]
