# Generated by Django 3.2.8 on 2021-11-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_eventbody_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbody',
            name='time',
            field=models.TimeField(),
        ),
    ]
