# Generated by Django 3.2.8 on 2021-11-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_eventbody_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbody',
            name='duration',
            field=models.TimeField(),
        ),
    ]
