# Generated by Django 3.2.8 on 2021-11-09 18:48

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_eventbody_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbody',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
