# Generated by Django 3.2.8 on 2021-12-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbody',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventbody',
            name='long',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
