# Generated by Django 3.2.8 on 2021-11-09 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_eventbody_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='body',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='events.eventbody'),
        ),
    ]
