# Generated by Django 3.2.3 on 2021-05-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('hashed_pw', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('description', models.TextField(max_length=250, null=True)),
                ('age', models.CharField(max_length=50, null=True)),
                ('location', models.CharField(max_length=60, null=True)),
            ],
        )
    ]
