# Generated by Django 3.2.3 on 2021-06-05 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210527_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=50, unique=True)),
                ('sportType', models.CharField(max_length=50)),
                ('numOfPlayers', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('date', models.TextField(blank=True, max_length=250, null=True)),
                ('time', models.TextField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
