# Generated by Django 3.2.3 on 2021-06-07 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210606_0116'),
        ('api', '0003_eventpost'),
    ]

    operations = [
    ]
